# Telegram MCP server — Telethon-backed, talks to Telegram as a *user*
# account (not a bot), so it needs an API id/hash pair from
# https://my.telegram.org plus a session string generated by the
# `telegram-mcp-generate-session` script this package also installs.
#
# Upstream's newest tag (v3.2.9, 2026-07-27) is older than the default branch
# and its tags do not track the version declared in pyproject.toml — every tag
# so far still says 2.0.1 — so this pins a commit and uses the nixpkgs
# `-unstable-<date>` convention. Advance both together.
{
  lib,
  fetchFromGitHub,
  python3Packages,
}:

python3Packages.buildPythonApplication {
  pname = "telegram-mcp";
  version = "2.0.1-unstable-2026-08-19";

  src = fetchFromGitHub {
    owner = "chigwell";
    repo = "telegram-mcp";
    rev = "a61294362226bd93052f5a40b4a1b1269a99ce69";
    hash = "sha256-k1luZ6eUY7o+LIjcHtrSRewTOEu3BX8sdvKFf2wiAUs=";
  };

  pyproject = true;

  build-system = with python3Packages; [ setuptools ];

  # `dotenv` is the PyPI shim around python-dotenv, which is also declared and
  # is what actually provides the `dotenv` module. It is not in nixpkgs and
  # nothing here needs it.
  pythonRemoveDeps = [ "dotenv" ];

  dependencies = with python3Packages; [
    httpx
    mcp
    python-dotenv
    python-json-logger
    qrcode
    telethon
  ];

  optional-dependencies = {
    # Only read when TELEGRAM_PROXY_TYPE is set.
    proxy = [ python3Packages.python-socks ];
  };

  # `telegram_mcp.install_guard` refuses to start unless the installed
  # distribution records a git or file:// origin, because the `telegram-mcp`
  # name on PyPI belongs to an unrelated project. A wheel built by nixpkgs
  # records no `direct_url.json` and ships no pyproject.toml, so the guard
  # fires on every one of its four call sites and the server exits at import.
  #
  # The premise does not hold here: `src` above IS an explicit, hash-pinned
  # fetch of that git repository, which is a stronger provenance guarantee
  # than the metadata the guard inspects. So satisfy the check at the one
  # predicate all four call sites reach, by asserting the origin the guard
  # cannot see for itself. `--replace-fail` turns any upstream rewrite of this
  # logic into a build error rather than a silent re-enable.
  postPatch = ''
    substituteInPlace telegram_mcp/install_guard.py \
      --replace-fail \
        '_direct_url_is_explicit_source_install(identity.direct_url)' \
        'True  # nix: origin is the hash-pinned fetchFromGitHub above'
  '';

  # `telegram_mcp.runtime` does its whole bootstrap at module scope: it casts
  # TELEGRAM_API_ID with int(), constructs a Telethon client (which rejects an
  # empty api_id/api_hash), and `sys.exit(1)`s if no session is configured. So
  # merely *importing* the server needs all three set.
  #
  # These are build-time env only, and deliberately a *named* session rather
  # than a session string: Telethon opens a named session as a local file and
  # touches no network, whereas StringSession would have to decode a real
  # session blob. Nothing connects during the check.
  env = {
    TELEGRAM_API_ID = "137";
    TELEGRAM_API_HASH = "nix-import-check";
    TELEGRAM_SESSION_NAME = "nix-import-check";
  };

  # Importing `main` runs the guard, so this also proves the patch above works.
  pythonImportsCheck = [
    "main"
    "telegram_mcp"
  ];

  meta = {
    description = "MCP server for Telegram, acting as a user account via Telethon";
    homepage = "https://github.com/chigwell/telegram-mcp";
    license = lib.licenses.asl20;
    maintainers = with lib.maintainers; [ antono ];
    mainProgram = "telegram-mcp";
  };
}
